version: "2"
services:
  app:
    build: .
    restart: always
    command: bash -c "rm -rf tmp/pids/server.pid && bundle exec rails server -p 3001 -b 0.0.0.0"
    stdin_open: true
    tty: true
    volumes:
      - ./:/app:cached
      - ./tmp/bundle:/usr/local/bundle
      - ${DOCKER_DATA_PATH}/${APP_NAME}/ImageMagick-6:/etc/ImageMagick-6
      - ${DOCKER_DATA_PATH}/${APP_NAME}/public/assets:/app/public/assets
    networks:
      - default
    ports:
      - 3001:3001
